# Basic NumPy Functionality
### Numpy n-dim Array
* Part of a data excosystem which includes data science libraries, ML and image processing
* huge and very powerful
* optimized array, better than lists
* can be any number of dimensions, typically 1 or 2 dims.
* restricted to a single data type across ALL dimesions
* required to dimension your arrays when initialized.

In [1]:
import numpy as np

In [3]:
l = [1, 2, 3]
a = np.array([1,2,3])

In [4]:
a

array([1, 2, 3])

In [5]:
l + l

[1, 2, 3, 1, 2, 3]

In [6]:
l * 5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [8]:
a + a       # vectorized math
a * 5


array([ 5, 10, 15])

In [9]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Performance

In [12]:
big_arr = np.arange(5e6)
big_list = list(range(int(5e6)))

In [14]:
%timeit -n5 x = [num ** 2 for num in big_list]

308 ms ± 3.63 ms per loop (mean ± std. dev. of 7 runs, 5 loops each)


In [16]:
%timeit -n5 x = big_arr ** 2

13 ms ± 1.81 ms per loop (mean ± std. dev. of 7 runs, 5 loops each)


## Determining Dimensions
* size = "rows" * "columns"
* itemsize --> number of bytes used by a single value
* itemsize * size = bytes of memory the array uses
* shape -> comma seeprated tuple of length of each dimension
* ndim -> int value of dimensions present
* reschape -> dimension manipulation

In [17]:
a = np.arange(15)

In [18]:
a.size      # how many elements

15

In [19]:
a.itemsize      # how much memory each element takes up (bytes)

4

In [21]:
big_arr.itemsize * big_arr.size     # how much memory big-arr takes up (4mb)

40000000

In [22]:
a.ndim

1

In [23]:
a.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [24]:
a.reshape(3,5).ndim

2

In [25]:
a.reshape(3, 5).shape       # (rows, columns)

(3, 5)

## Slicing

In [26]:
a[0]

0

In [27]:
a = a.reshape(3,5)

In [28]:
a[0] # first row

array([0, 1, 2, 3, 4])

In [29]:
a[0,0]  # first column first row

0

In [30]:
a[:,0]      # first column

array([ 0,  5, 10])

In [ ]:
a[1,:]      # second row

## Special Arrays
* useful for dimensioning an array before you know what values it will hold

In [31]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [33]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [32]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
np.dot(np.eye(5,5), np.eye(5,5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Standard normal
* mean 0
* std 1
* takes a single optional argument -> n
* np.random.standard_normal([size])

In [36]:
np.random.standard_normal(5)

array([0.06838075, 0.17959404, 0.24853123, 0.32052574, 0.07854066])

In [37]:
x = np.random.standard_normal(50000)

In [38]:
import numpy.random as npr

In [59]:
npr.normal(10, 5)   #mean, standard deviation

12.331711251666185

## Uniform Distributions
* np.random.randn(size=None)
* np.random.randint(low, high=None, size=None, dtype=int)
    * excludes high -> called a a half-open interval

In [61]:
npr.randn()

0.8757066227308175

In [83]:
npr.randint(1,7)


3

## Normal

In [84]:
print(x.mean())
print(x.std())
print(x.max())
print(x.min())

# no median function!

-1.1598416915364922e-05
1.0038998974169073
4.101121876936035
-4.229961911672463


In [86]:
percentiles = [2.5, 5, 50, 95, 97.5]
np.percentile(x, percentiles)

array([-1.97200309, -1.65405962, -0.00260424,  1.64449858,  1.97019695])

## Simple Linear Modeling

In [88]:
x = npr.normal(size = 50) * 100
y = x + 5 * npr.normal(size=50)

In [89]:
np.corrcoef(x,y)

array([[1.        , 0.99841204],
       [0.99841204, 1.        ]])

In [90]:
np.polyfit(x, y, deg = 1)

array([ 1.00922755, -0.32057408])

## fill array with unformly spaced data points between a min and max

In [91]:
np.linspace(-4, 4, 10)

array([-4.        , -3.11111111, -2.22222222, -1.33333333, -0.44444444,
        0.44444444,  1.33333333,  2.22222222,  3.11111111,  4.        ])